publishDir = "docs"
languageCode = "en-us"
title = "Hugo on GitHub Pages"
theme = "hugo-book"
canonifyURLs = true
uglyURLs = true
baseURL = "https://zq-psk.github.io/ssg/"
# enableGitInfo = true
[params]
    BookRepo = 'https://github.com/ZQ-PSK/ssg'