publishDir = "docs"
languageCode = "en-us"
title = "Hugo on GitHub Pages"
theme = "hugo-book"
baseURL = "https://github.com/ZQ-PSK/ssg/"
# enableGitInfo = true
[params]
    BookRepo = 'https://github.com/ZQ-PSK/ssg'